import { InputNumber, Select } from "antd";
import React from "react";

const data = [
  {
    id: 1,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/af.svg",
    code: "+93",
    display: "+93 (Afghanistan)",
  },
  {
    id: 2,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/al.svg",
    code: "+355",
    display: "+355 (Albania)",
  },
  {
    id: 3,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/dz.svg",
    code: "+213",
    display: "+213 (Algeria)",
  },
  {
    id: 4,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/as.svg",
    code: "+1684",
    display: "+1684 (American Samoa)",
  },
  {
    id: 5,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ad.svg",
    code: "+376",
    display: "+376 (Andorra)",
  },
  {
    id: 6,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ao.svg",
    code: "+244",
    display: "+244 (Angola)",
  },
  {
    id: 7,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ai.svg",
    code: "+1264",
    display: "+1264 (Anguilla)",
  },
  {
    id: 8,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/aq.svg",
    code: "+672",
    display: "+672 (Antarctica)",
  },
  {
    id: 9,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ag.svg",
    code: "+1268",
    display: "+1268 (Antigua and Barbuda)",
  },
  {
    id: 10,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ar.svg",
    code: "+54",
    display: "+54 (Argentina)",
  },
  {
    id: 11,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/am.svg",
    code: "+374",
    display: "+374 (Armenia)",
  },
  {
    id: 12,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/aw.svg",
    code: "+297",
    display: "+297 (Aruba)",
  },
  {
    id: 13,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/au.svg",
    code: "+61",
    display: "+61 (Australia)",
  },
  {
    id: 14,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/at.svg",
    code: "+43",
    display: "+43 (Austria)",
  },
  {
    id: 15,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/az.svg",
    code: "+994",
    display: "+994 (Azerbaijan)",
  },
  {
    id: 16,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/bs.svg",
    code: "+1242",
    display: "+1242 (Bahamas)",
  },
  {
    id: 17,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/bh.svg",
    code: "+973",
    display: "+973 (Bahrain)",
  },
  {
    id: 18,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/bd.svg",
    code: "+880",
    display: "+880 (Bangladesh)",
  },
  {
    id: 19,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/bb.svg",
    code: "+1246",
    display: "+1246 (Barbados)",
  },
  {
    id: 20,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/by.svg",
    code: "+375",
    display: "+375 (Belarus)",
  },
  {
    id: 21,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/be.svg",
    code: "+32",
    display: "+32 (Belgium)",
  },
  {
    id: 22,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/bz.svg",
    code: "+501",
    display: "+501 (Belize)",
  },
  {
    id: 23,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/bj.svg",
    code: "+229",
    display: "+229 (Benin)",
  },
  {
    id: 24,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/bm.svg",
    code: "+1441",
    display: "+1441 (Bermuda)",
  },
  {
    id: 25,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/bt.svg",
    code: "+975",
    display: "+975 (Bhutan)",
  },
  {
    id: 26,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/bo.svg",
    code: "+591",
    display: "+591 (Bolivia)",
  },
  {
    id: 27,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ba.svg",
    code: "+387",
    display: "+387 (Bosnia and Herzegovina)",
  },
  {
    id: 28,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/bw.svg",
    code: "+267",
    display: "+267 (Botswana)",
  },
  {
    id: 29,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/br.svg",
    code: "+55",
    display: "+55 (Brazil)",
  },
  {
    id: 30,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/io.svg",
    code: "+246",
    display: "+246 (British Indian Ocean Territory)",
  },
  {
    id: 31,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/vg.svg",
    code: "+1284",
    display: "+1284 (British Virgin Islands)",
  },
  {
    id: 32,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/bn.svg",
    code: "+673",
    display: "+673 (Brunei)",
  },
  {
    id: 33,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/bg.svg",
    code: "+359",
    display: "+359 (Bulgaria)",
  },
  {
    id: 34,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/bf.svg",
    code: "+226",
    display: "+226 (Burkina Faso)",
  },
  {
    id: 35,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/bi.svg",
    code: "+257",
    display: "+257 (Burundi)",
  },
  {
    id: 36,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/kh.svg",
    code: "+855",
    display: "+855 (Cambodia)",
  },
  {
    id: 37,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/cm.svg",
    code: "+237",
    display: "+237 (Cameroon)",
  },
  {
    id: 38,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ca.svg",
    code: "+1",
    display: "+1 (Canada)",
  },
  {
    id: 39,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/cv.svg",
    code: "+238",
    display: "+238 (Cape Verde)",
  },
  {
    id: 40,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ky.svg",
    code: "+1345",
    display: "+1345 (Cayman Islands)",
  },
  {
    id: 41,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/cf.svg",
    code: "+236",
    display: "+236 (Central African Republic)",
  },
  {
    id: 42,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/td.svg",
    code: "+235",
    display: "+235 (Chad)",
  },
  {
    id: 43,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/4x3/cl.svg",
    code: "+56",
    display: "+56 (Chile)",
  },
  {
    id: 44,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/cn.svg",
    code: "+86",
    display: "+86 (China)",
  },
  {
    id: 45,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/cx.svg",
    code: "+61",
    display: "+61 (Christmas Island)",
  },
  {
    id: 46,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/4x3/cc.svg",
    code: "+61",
    display: "+61 (Cocos Islands)",
  },
  {
    id: 47,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/co.svg",
    code: "+57",
    display: "+57 (Colombia)",
  },
  {
    id: 48,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/km.svg",
    code: "+269",
    display: "+269 (Comoros)",
  },
  {
    id: 49,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ck.svg",
    code: "+682",
    display: "+682 (Cook Islands)",
  },
  {
    id: 50,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/cr.svg",
    code: "+506",
    display: "+506 (Costa Rica)",
  },
  {
    id: 51,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/hr.svg",
    code: "+385",
    display: "+385 (Croatia)",
  },
  {
    id: 52,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/cu.svg",
    code: "+53",
    display: "+53 (Cuba)",
  },
  {
    id: 53,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/cw.svg",
    code: "+599",
    display: "+599 (Curacao)",
  },
  {
    id: 54,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/cy.svg",
    code: "+357",
    display: "+357 (Cyprus)",
  },
  {
    id: 55,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/cz.svg",
    code: "+420",
    display: "+420 (Czech Republic)",
  },
  {
    id: 56,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/cd.svg",
    code: "+243",
    display: "+243 (Democratic Republic of the Congo)",
  },
  {
    id: 57,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/dk.svg",
    code: "+45",
    display: "+45 (Denmark)",
  },
  {
    id: 58,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/dj.svg",
    code: "+253",
    display: "+253 (Djibouti)",
  },
  {
    id: 59,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/dm.svg",
    code: "+1767",
    display: "+1767 (Dominica)",
  },
  {
    id: 60,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/do.svg",
    code: "+1809, 1829, 1849",
    display: "+1809, 1829, 1849 (Dominican Republic)",
  },
  {
    id: 61,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/tl.svg",
    code: "+670",
    display: "+670 (East Timor)",
  },
  {
    id: 62,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ec.svg",
    code: "+593",
    display: "+593 (Ecuador)",
  },
  {
    id: 63,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/eg.svg",
    code: "+20",
    display: "+20 (Egypt)",
  },
  {
    id: 64,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/sv.svg",
    code: "+503",
    display: "+503 (El Salvador)",
  },
  {
    id: 65,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/gg.svg",
    code: "+240",
    display: "+240 (Equatorial Guinea)",
  },
  {
    id: 66,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/er.svg",
    code: "+291",
    display: "+291 (Eritrea)",
  },
  {
    id: 67,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ee.svg",
    code: "+372",
    display: "+372 (Estonia)",
  },
  {
    id: 68,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/et.svg",
    code: "+251",
    display: "+251 (Ethiopia)",
  },
  {
    id: 69,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/fk.svg",
    code: "+500",
    display: "+500 (Falkland Islands)",
  },
  {
    id: 70,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/fo.svg",
    code: "+298",
    display: "+298 (Faroe Islands)",
  },
  {
    id: 71,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/fj.svg",
    code: "+679",
    display: "+679 (Fiji)",
  },
  {
    id: 72,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/fi.svg",
    code: "+358",
    display: "+358 (Finland)",
  },
  {
    id: 73,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/fr.svg",
    code: "+33",
    display: "+33 (France)",
  },
  {
    id: 74,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/pf.svg",
    code: "+689",
    display: "+689 (French Polynesia)",
  },
  {
    id: 75,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ga.svg",
    code: "+241",
    display: "+241 (Gabon)",
  },
  {
    id: 76,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/gm.svg",
    code: "+220",
    display: "+220 (Gambia)",
  },
  {
    id: 77,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ge.svg",
    code: "+995",
    display: "+995 (Georgia)",
  },
  {
    id: 78,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/de.svg",
    code: "+49",
    display: "+49 (Germany)",
  },
  {
    id: 79,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/gh.svg",
    code: "+233",
    display: "+233 (Ghana)",
  },
  {
    id: 80,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/gi.svg",
    code: "+350",
    display: "+350 (Gibraltar)",
  },
  {
    id: 81,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/gr.svg",
    code: "+30",
    display: "+30 (Greece)",
  },
  {
    id: 82,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/gl.svg",
    code: "+299",
    display: "+299 (Greenland)",
  },
  {
    id: 83,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/4x3/gd.svg",
    code: "+1473",
    display: "+1473 (Grenada)",
  },
  {
    id: 84,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/gu.svg",
    code: "+1671",
    display: "+1671 (Guam)",
  },
  {
    id: 85,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/gt.svg",
    code: "+502",
    display: "+502 (Guatemala)",
  },
  {
    id: 86,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/gg.svg",
    code: "+441481",
    display: "+441481 (Guernsey)",
  },
  {
    id: 87,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/gn.svg",
    code: "+224",
    display: "+224 (Guinea)",
  },
  {
    id: 88,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/gw.svg",
    code: "+245",
    display: "+245 (Guinea-Bissau)",
  },
  {
    id: 89,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/gy.svg",
    code: "+592",
    display: "+592 (Guyana)",
  },
  {
    id: 90,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ht.svg",
    code: "+509",
    display: "+509 (Haiti)",
  },
  {
    id: 91,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/hn.svg",
    code: "+504",
    display: "+504 (Honduras)",
  },
  {
    id: 92,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/hk.svg",
    code: "+852",
    display: "+852 (Hong Kong)",
  },
  {
    id: 93,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/hu.svg",
    code: "+36",
    display: "+36 (Hungary)",
  },
  {
    id: 94,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/is.svg",
    code: "+354",
    display: "+354 (Iceland)",
  },
  {
    id: 95,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/in.svg",
    code: "+91",
    display: "+91 (India)",
  },
  {
    id: 96,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/id.svg",
    code: "+62",
    display: "+62 (Indonesia)",
  },
  {
    id: 97,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ir.svg",
    code: "+98",
    display: "+98 (Iran)",
  },
  {
    id: 98,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/iq.svg",
    code: "+964",
    display: "+964 (Iraq)",
  },
  {
    id: 99,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ie.svg",
    code: "+353",
    display: "+353 (Ireland)",
  },
  {
    id: 100,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/im.svg",
    code: "+441624",
    display: "+441624 (Isle of Man)",
  },
  {
    id: 101,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/il.svg",
    code: "+972",
    display: "+972 (Israel)",
  },
  {
    id: 102,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/it.svg",
    code: "+39",
    display: "+39 (Italy)",
  },
  {
    id: 103,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ci.svg",
    code: "+225",
    display: "+225 (Ivory Coast)",
  },
  {
    id: 104,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/jm.svg",
    code: "+1876",
    display: "+1876 (Jamaica)",
  },
  {
    id: 105,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/jp.svg",
    code: "+81",
    display: "+81 (Japan)",
  },
  {
    id: 106,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/je.svg",
    code: "+441534",
    display: "+441534 (Jersey)",
  },
  {
    id: 107,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/jo.svg",
    code: "+962",
    display: "+962 (Jordan)",
  },
  {
    id: 108,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/kz.svg",
    code: "+7",
    display: "+7 (Kazakhstan)",
  },
  {
    id: 109,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ke.svg",
    code: "+254",
    display: "+254 (Kenya)",
  },
  {
    id: 110,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ki.svg",
    code: "+686",
    display: "+686 (Kiribati)",
  },
  {
    id: 111,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/xk.svg",
    code: "+383",
    display: "+383 (Kosovo)",
  },
  {
    id: 112,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/kw.svg",
    code: "+965",
    display: "+965 (Kuwait)",
  },
  {
    id: 113,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/kg.svg",
    code: "+996",
    display: "+996 (Kyrgyzstan)",
  },
  {
    id: 114,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/la.svg",
    code: "+856",
    display: "+856 (Laos)",
  },
  {
    id: 115,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/lv.svg",
    code: "+371",
    display: "+371 (Latvia)",
  },
  {
    id: 116,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/lb.svg",
    code: "+961",
    display: "+961 (Lebanon)",
  },
  {
    id: 117,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ls.svg",
    code: "+266",
    display: "+266 (Lesotho)",
  },
  {
    id: 118,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/lr.svg",
    code: "+231",
    display: "+231 (Liberia)",
  },
  {
    id: 119,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ly.svg",
    code: "+218",
    display: "+218 (Libya)",
  },
  {
    id: 120,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/li.svg",
    code: "+423",
    display: "+423 (Liechtenstein)",
  },
  {
    id: 121,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/lt.svg",
    code: "+370",
    display: "+370 (Lithuania)",
  },
  {
    id: 122,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/lu.svg",
    code: "+352",
    display: "+352 (Luxembourg)",
  },
  {
    id: 123,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/mo.svg",
    code: "+853",
    display: "+853 (Macau)",
  },
  {
    id: 124,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/mk.svg",
    code: "+389",
    display: "+389 (Macedonia)",
  },
  {
    id: 125,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/mg.svg",
    code: "+261",
    display: "+261 (Madagascar)",
  },
  {
    id: 126,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/mw.svg",
    code: "+265",
    display: "+265 (Malawi)",
  },
  {
    id: 127,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/my.svg",
    code: "+60",
    display: "+60 (Malaysia)",
  },
  {
    id: 128,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/mv.svg",
    code: "+960",
    display: "+960 (Maldives)",
  },
  {
    id: 129,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ml.svg",
    code: "+223",
    display: "+223 (Mali)",
  },
  {
    id: 130,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/mt.svg",
    code: "+356",
    display: "+356 (Malta)",
  },
  {
    id: 131,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/mh.svg",
    code: "+692",
    display: "+692 (Marshall Islands)",
  },
  {
    id: 132,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/mr.svg",
    code: "+222",
    display: "+222 (Mauritania)",
  },
  {
    id: 133,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/mu.svg",
    code: "+230",
    display: "+230 (Mauritius)",
  },
  {
    id: 134,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/yt.svg",
    code: "+262",
    display: "+262 (Mayotte)",
  },
  {
    id: 135,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/mx.svg",
    code: "+52",
    display: "+52 (Mexico)",
  },
  {
    id: 136,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/fm.svg",
    code: "+691",
    display: "+691 (Micronesia)",
  },
  {
    id: 137,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/md.svg",
    code: "+373",
    display: "+373 (Moldova)",
  },
  {
    id: 138,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/mc.svg",
    code: "+377",
    display: "+377 (Monaco)",
  },
  {
    id: 139,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/mn.svg",
    code: "+976",
    display: "+976 (Mongolia)",
  },
  {
    id: 140,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/me.svg",
    code: "+382",
    display: "+382 (Montenegro)",
  },
  {
    id: 141,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ms.svg",
    code: "+1664",
    display: "+1664 (Montserrat)",
  },
  {
    id: 142,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ma.svg",
    code: "+212",
    display: "+212 (Morocco)",
  },
  {
    id: 143,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/mz.svg",
    code: "+258",
    display: "+258 (Mozambique)",
  },
  {
    id: 144,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/mm.svg",
    code: "+95",
    display: "+95 (Myanmar)",
  },
  {
    id: 145,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/na.svg",
    code: "+264",
    display: "+264 (Namibia)",
  },
  {
    id: 146,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/nr.svg",
    code: "+674",
    display: "+674 (Nauru)",
  },
  {
    id: 147,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/np.svg",
    code: "+977",
    display: "+977 (Nepal)",
  },
  {
    id: 148,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/nl.svg",
    code: "+31",
    display: "+31 (Netherlands)",
  },
  {
    id: 149,
    flag: "https://www.countryflags.io/an/flat/64.png",
    code: "+599",
    display: "+599 (Netherlands Antilles)",
  },
  {
    id: 150,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/nc.svg",
    code: "+687",
    display: "+687 (New Caledonia)",
  },
  {
    id: 151,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/nz.svg",
    code: "+64",
    display: "+64 (New Zealand)",
  },
  {
    id: 152,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ni.svg",
    code: "+505",
    display: "+505 (Nicaragua)",
  },
  {
    id: 153,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ne.svg",
    code: "+227",
    display: "+227 (Niger)",
  },
  {
    id: 154,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ng.svg",
    code: "+234",
    display: "+234 (Nigeria)",
  },
  {
    id: 155,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/nu.svg",
    code: "+683",
    display: "+683 (Niue)",
  },
  {
    id: 156,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/kp.svg",
    code: "+850",
    display: "+850 (North Korea)",
  },
  {
    id: 157,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/mp.svg",
    code: "+1670",
    display: "+1670 (Northern Mariana Islands)",
  },
  {
    id: 158,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/no.svg",
    code: "+47",
    display: "+47 (Norway)",
  },
  {
    id: 159,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/om.svg",
    code: "+968",
    display: "+968 (Oman)",
  },
  {
    id: 160,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/pk.svg",
    code: "+92",
    display: "+92 (Pakistan)",
  },
  {
    id: 161,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/pw.svg",
    code: "+680",
    display: "+680 (Palau)",
  },
  {
    id: 162,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ps.svg",
    code: "+970",
    display: "+970 (Palestine)",
  },
  {
    id: 163,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/pa.svg",
    code: "+507",
    display: "+507 (Panama)",
  },
  {
    id: 164,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/pg.svg",
    code: "+675",
    display: "+675 (Papua New Guinea)",
  },
  {
    id: 165,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/py.svg",
    code: "+595",
    display: "+595 (Paraguay)",
  },
  {
    id: 166,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/pe.svg",
    code: "+51",
    display: "+51 (Peru)",
  },
  {
    id: 167,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ph.svg",
    code: "+63",
    display: "+63 (Philippines)",
  },
  {
    id: 168,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/pn.svg",
    code: "+64",
    display: "+64 (Pitcairn)",
  },
  {
    id: 169,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/pl.svg",
    code: "+48",
    display: "+48 (Poland)",
  },
  {
    id: 170,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/pt.svg",
    code: "+351",
    display: "+351 (Portugal)",
  },
  {
    id: 171,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/pr.svg",
    code: "+1787, 1939",
    display: "+1787, 1939 (Puerto Rico)",
  },
  {
    id: 172,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/qa.svg",
    code: "+974",
    display: "+974 (Qatar)",
  },
  {
    id: 173,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/cg.svg",
    code: "+242",
    display: "+242 (Republic of the Congo)",
  },
  {
    id: 174,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/re.svg",
    code: "+262",
    display: "+262 (Reunion)",
  },
  {
    id: 175,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ro.svg",
    code: "+40",
    display: "+40 (Romania)",
  },
  {
    id: 176,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ru.svg",
    code: "+7",
    display: "+7 (Russia)",
  },
  {
    id: 177,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/rw.svg",
    code: "+250",
    display: "+250 (Rwanda)",
  },
  {
    id: 178,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/bl.svg",
    code: "+590",
    display: "+590 (Saint Barthelemy)",
  },
  {
    id: 179,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/sh.svg",
    code: "+290",
    display: "+290 (Saint Helena)",
  },
  {
    id: 180,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/kn.svg",
    code: "+1869",
    display: "+1869 (Saint Kitts and Nevis)",
  },
  {
    id: 181,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/lc.svg",
    code: "+1758",
    display: "+1758 (Saint Lucia)",
  },
  {
    id: 182,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/mf.svg",
    code: "+590",
    display: "+590 (Saint Martin)",
  },
  {
    id: 183,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/pm.svg",
    code: "+508",
    display: "+508 (Saint Pierre and Miquelon)",
  },
  {
    id: 184,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/vc.svg",
    code: "+1784",
    display: "+1784 (Saint Vincent and the Grenadines)",
  },
  {
    id: 185,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ws.svg",
    code: "+685",
    display: "+685 (Samoa)",
  },
  {
    id: 186,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/sm.svg",
    code: "+378",
    display: "+378 (San Marino)",
  },
  {
    id: 187,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/st.svg",
    code: "+239",
    display: "+239 (Sao Tome and Principe)",
  },
  {
    id: 188,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/sa.svg",
    code: "+966",
    display: "+966 (Saudi Arabia)",
  },
  {
    id: 189,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/sn.svg",
    code: "+221",
    display: "+221 (Senegal)",
  },
  {
    id: 190,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/rs.svg",
    code: "+381",
    display: "+381 (Serbia)",
  },
  {
    id: 191,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/sc.svg",
    code: "+248",
    display: "+248 (Seychelles)",
  },
  {
    id: 192,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/sl.svg",
    code: "+232",
    display: "+232 (Sierra Leone)",
  },
  {
    id: 193,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/sg.svg",
    code: "+65",
    display: "+65 (Singapore)",
  },
  {
    id: 194,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/sx.svg",
    code: "+1721",
    display: "+1721 (Sint Maarten)",
  },
  {
    id: 195,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/sk.svg",
    code: "+421",
    display: "+421 (Slovakia)",
  },
  {
    id: 196,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/si.svg",
    code: "+386",
    display: "+386 (Slovenia)",
  },
  {
    id: 197,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/sb.svg",
    code: "+677",
    display: "+677 (Solomon Islands)",
  },
  {
    id: 198,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/so.svg",
    code: "+252",
    display: "+252 (Somalia)",
  },
  {
    id: 199,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/za.svg",
    code: "+27",
    display: "+27 (South Africa)",
  },
  {
    id: 200,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/kr.svg",
    code: "+82",
    display: "+82 (South Korea)",
  },
  {
    id: 201,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ss.svg",
    code: "+211",
    display: "+211 (South Sudan)",
  },
  {
    id: 202,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/es.svg",
    code: "+34",
    display: "+34 (Spain)",
  },
  {
    id: 203,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/lk.svg",
    code: "+94",
    display: "+94 (Sri Lanka)",
  },
  {
    id: 204,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/sd.svg",
    code: "+249",
    display: "+249 (Sudan)",
  },
  {
    id: 205,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/sr.svg",
    code: "+597",
    display: "+597 (Suriname)",
  },
  {
    id: 206,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/sj.svg",
    code: "+47",
    display: "+47 (Svalbard and Jan Mayen)",
  },
  {
    id: 207,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/sz.svg",
    code: "+268",
    display: "+268 (Swaziland)",
  },
  {
    id: 208,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/se.svg",
    code: "+46",
    display: "+46 (Sweden)",
  },
  {
    id: 209,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ch.svg",
    code: "+41",
    display: "+41 (Switzerland)",
  },
  {
    id: 210,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/sy.svg",
    code: "+963",
    display: "+963 (Syria)",
  },
  {
    id: 211,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/tw.svg",
    code: "+886",
    display: "+886 (Taiwan)",
  },
  {
    id: 212,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/tj.svg",
    code: "+992",
    display: "+992 (Tajikistan)",
  },
  {
    id: 213,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/tz.svg",
    code: "+255",
    display: "+255 (Tanzania)",
  },
  {
    id: 214,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/th.svg",
    code: "+66",
    display: "+66 (Thailand)",
  },
  {
    id: 215,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/tg.svg",
    code: "+228",
    display: "+228 (Togo)",
  },
  {
    id: 216,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/4x3/tk.svg",
    code: "+690",
    display: "+690 (Tokelau)",
  },
  {
    id: 217,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/to.svg",
    code: "+676",
    display: "+676 (Tonga)",
  },
  {
    id: 218,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/tt.svg",
    code: "+1868",
    display: "+1868 (Trinidad and Tobago)",
  },
  {
    id: 219,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/tn.svg",
    code: "+216",
    display: "+216 (Tunisia)",
  },
  {
    id: 220,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/tr.svg",
    code: "+90",
    display: "+90 (Turkey)",
  },
  {
    id: 221,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/tm.svg",
    code: "+993",
    display: "+993 (Turkmenistan)",
  },
  {
    id: 222,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/tc.svg",
    code: "+1649",
    display: "+1649 (Turks and Caicos Islands)",
  },
  {
    id: 223,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/tv.svg",
    code: "+688",
    display: "+688 (Tuvalu)",
  },
  {
    id: 224,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/vi.svg",
    code: "+1340",
    display: "+1340 (U.S. Virgin Islands)",
  },
  {
    id: 225,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ug.svg",
    code: "+256",
    display: "+256 (Uganda)",
  },
  {
    id: 226,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ua.svg",
    code: "+380",
    display: "+380 (Ukraine)",
  },
  {
    id: 227,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ae.svg",
    code: "+971",
    display: "+971 (United Arab Emirates)",
  },
  {
    id: 228,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/gb.svg",
    code: "+44",
    display: "+44 (United Kingdom)",
  },
  {
    id: 229,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/us.svg",
    code: "+1",
    display: "+1 (United States)",
  },
  {
    id: 230,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/uy.svg",
    code: "+598",
    display: "+598 (Uruguay)",
  },
  {
    id: 231,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/uz.svg",
    code: "+998",
    display: "+998 (Uzbekistan)",
  },
  {
    id: 232,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/vu.svg",
    code: "+678",
    display: "+678 (Vanuatu)",
  },
  {
    id: 233,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/va.svg",
    code: "+379",
    display: "+379 (Vatican)",
  },
  {
    id: 234,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ve.svg",
    code: "+58",
    display: "+58 (Venezuela)",
  },
  {
    id: 235,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/vn.svg",
    code: "+84",
    display: "+84 (Vietnam)",
  },
  {
    id: 236,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/wf.svg",
    code: "+681",
    display: "+681 (Wallis and Futuna)",
  },
  {
    id: 237,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/eh.svg",
    code: "+212",
    display: "+212 (Western Sahara)",
  },
  {
    id: 238,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/ye.svg",
    code: "+967",
    display: "+967 (Yemen)",
  },
  {
    id: 239,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/zm.svg",
    code: "+260",
    display: "+260 (Zambia)",
  },
  {
    id: 240,
    flag: "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/flags/1x1/zw.svg",
    code: "+263",
    display: "+263 (Zimbabwe)",
  },
];

export default function PhoneNumber() {
  return (
      <InputNumber
        style={{width: "100%"}}
        addonBefore={
          <Select
            style={{
              width: 100,
            }}
            defaultValue="+91"
            className="phn-dropdown"
          >
            {data.map((each) => (
              <Select.Option key={each.id} value={each.code}>
                <img style={{ height: 14, width: 14 }} src={each.flag}></img>

                <span>{each.code}</span>
              </Select.Option>
            ))}
          </Select>
        }
        maxLength={10}
        controls={false}
        type="number"
      />
  );
}
